on: 
  push:
    branches:
      - master
name: Publish Website over SFTP
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Install npm dependencies
        run: npm ci
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: railway-stations.org
          FTP_USERNAME: rswebsitesftp
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          REMOTE_DIR: map
          METHOD: sftp
          ARGS: --delete-excluded --exclude=.sonarcloud.properties --exclude-glob=.git*/** --exclude-glob=.git** --exclude-glob=composer* --exclude-glob=package* --exclude-glob=node_modules/** --exclude-glob=js/  --exclude-glob=css/ 
